services:
  rosys:
    image: "zauberzeug/rosys:${TAG-latest}"
    volumes:
      - ./:/rosys
      - ./:/app
      - ./../nicegui/nicegui:/usr/local/lib/python3.11/site-packages/nicegui
      - ~/.vscode-server:/root/.vscode-server
      - ~/.rosys:/root/.rosys
    privileged: true
    ports:
      - 80:8080
    environment:
      - TZ=Europe/Amsterdam
      - ROBOT_ID=${ROBOT_ID}
    build:
      context: ./
      args:
        INSTALL_DEV: "true"
    cap_add:
      - SYS_NICE # allow container to set process priorities
      - SYS_PTRACE # allow profiling with py-spy
    hostname: docker
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "100"
    command: /rosys/start.sh debug
