name: Run Tests

on: workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  checker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install 3.11
      - name: Install dependencies
        run: uv sync
      - name: pre-commit, mypy and pylint
        run: |
          uv run pre-commit run --all-files
          uv run mypy ./rosys --non-interactive
          uv run pylint ./rosys

  pytest:
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install ${{ matrix.python }}
      - name: Install dependencies
        run: |
          uv sync
          sudo apt-get update && sudo apt-get install -y v4l-utils psmisc
      - name: test
        run: uv run pytest
      - name: examples
        run: cd tests && uv run ./test_examples.py
